apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworld-go
  namespace: default
spec:
  template:
    spec:
      containers:
      - image: docker.iblabs.ir/knative/helloworld-go:latest
        env:
        - name: TARGET
          value: "Go Sample v1"